
sudo: false # route build to the container-based infrastructure for a faster build

before_install:
  - gem install sass

language: node_js
node_js:
  - node # implies latest version

cache:
  directories:
    - node_modules

env:
  global:
    - TZ="America/Los_Angeles" # for Headless Chrome. otherwise will be UTC, bad for tests
  matrix:
    - CMD=test-ci
    - CMD=lint

# TODO: instead of flag, use env variable TRAVIS
# https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
script: npm run $CMD -- --travis
